### PR TITLE
Modularize + add varjo as git submodule

### PR DESCRIPTION
**Pull request by nixz**

### CODE REVIEW

**Comment by nixz** [comment]
Still work in progress... For now I have been keeping up with your changes in master...

**Comment by nixz** [comment]
Got things to compile

**Comment by cbaggers** [comment]
cepl and varjo have mutated too far to bring this in. I'm sorry. I have done a lot of work with submodules since this opened and have decided that I'm not the biggest fan.

**Comment by nixz** [comment]
Sounds good

**Pull request closed without merging**
