### PR TITLE
Proofreading

### PR DESCRIPTION
**Pull request by stacksmith**
@cbaggers, I took the liberty of proofreading all the .md files (documentation and front matter) and making corrections where needed.  I think this merge will help as the documentation is a bit out of date, full of typos and sometimes just doesn't make sense.

It may be easier to just view the updated .md files [in my fork](https://github.com/stacksmith/cepl); see proofreading branch.

The fixes include:

- outright typos and linguistic issues
- outdated code in chapter 001, code now runs
- numbered callouts in chapter 001 that were not documented fully; comments in code make more sense
- all references to CEPL are capitalized, as the readme.md file introduces CEPL that way
- references to OpenGL, CFFI, Common Lisp, etc. capitalized in a consistent way
- minor sentence restructuring throughout.  I attempted to preserve a conversational tone, while streamlining the pronoun usage (we, you, etc) and changed some clumsy parts
- fixed incorrect references to chapters as they were obviously renumbered at some point
- converted some parts to tables as made sense
- cleaned up and tagged lisp examples with Lisp syntax coloring

There is more work to be done, especially with missing chapters.

### CODE REVIEW

**Comment by stacksmith** [comment]
Proofread all md files

**Comment by cbaggers** [comment]
Once again, incredible work. I can't stress enough how valuable this is to the project (I'm sure you understand this already but please indulge my giddyness :) )

I'm happy to merge all of this. I have neglected the guides for a long time quite simply because they are much harder that coding. I will go through and check that the code snippets still work as the api has changed since I wrote these (especially around fbos)

Thankyou

**Comment by stacksmith** [comment]
My pleasure.  I love this project, and will do what I can to help.
Unfortunately, there are a few more typos that slipped past me, including ones in the main project readme file...  I will send another pull request very soon. 

I wish there was a way to do this without bugging you about every typo.  I don't think it's possible on Github to add a collaborator for only some part of the source tree, but possibly for a branch?  Probably not.

**Comment by cbaggers** [comment]
Then I'll just give you access to the lot :) Unless changes are trivial (like small numbers of typos) I'd like us to work in branches and merge as this gives us clear history of what happened where. Standard stuff really, we can work out the rest on the fly

**Comment by stacksmith** [comment]
Got it.  Thanks!

**Pull request merged**
