### PR TITLE
Formating bug on error message.

### PR DESCRIPTION
**Pull request by graysoncroom**
The error contained the message:
 ```
(ERROR "Cepl requires OpenGL 3.1 or higher. Found ~a.~a" 
        (CL-OPENGL:MAJOR-VERSION) 
        (CL_OPENGL:MINOR_VERSION))
```
Instead of outputting a message like:
`(ERROR "Cepl requires OpenGL 3.1 or higher. Found: 3.0")`

It looks like to me that the issue is that a call to the function 'format' was forgotten. I wrapped the string and two variables in format where it will pass the generated message as an argument to the error function.
```
(error (format nil 
               "Cepl requires OpenGL 3.1 or higher. Found ~a.~a"  
               (CL-OPENGL:MAJOR-VERSION) 
               (CL_OPENGL:MINOR_VERSION)))
```

I did not think I need to create an issue for this, because the bug was so easy to track down and fix. If you want/need me to make an issue for it just let me know.

I also spotted a misspelling on the README.md ( Whist -> Whilst ).
**Whist** is a card game
**Whilst** is the British english adverb form of while.
 
Not super helpful, but I am trying to get into open source by working on small things first. Let me know if there is any other easy (read: boring) tasks you need done! :-)

### CODE REVIEW

**Comment by cbaggers** [comment]
Thanks for the spelling fix, that stuff is super useful. 

But the other part is incorrect. 
Try this in your REPL `(error "Hi ~a" 10)` and see the error in the debugger. It is quite common for implementations to also print out the code that raised the error (with ~a etc) which I find confusing. However the current way is correct.

**Comment by cbaggers** [comment]
I've pulled in your change here https://github.com/cbaggers/cepl/commit/bcefd805d6826083df84a817a5006e64d6441240

So I think we can close this pr now :) thanks again

**Comment by graysoncroom** [comment]
When the error was printed to my screen **it was not formatted** as you would expect it to be. (look at the bottom of the picture)

picture

When I ran:
`(error "~a" 10)`
This is printed to standard output:
`(error 10)`

But when cepl threw the error the following was literately printed **without the expected formatting** to standard output:
```
(ERROR "Cepl requires OpenGL 3.1 or higher. Found ~a.~a" 
       (CL-OPENGL:MAJOR-VERSION) 
       (CL_OPENGL:MINOR_VERSION))
```
Not sure why but for some reason it was not being substituted as it should have been. So I tried to fix this by directly sticking in in the format function.

**Comment by cbaggers** [comment]
27012656-886ce20c-4e99-11e7-88db-1ebc15b66a18
A: is what I would expect to see. That's the formatted error
B: Is lisp reporting *where* the error was thrown

Also are you using lisp from the terminal? In my humble opinion if you arent using an editor with some kind of integration the experience of writing lisp is terrible. Emacs & Vim both have good support, Atom support is very WIP but is getting there. Some implementations (especially sbcl) don't ever expect anyone to use it straight from the nix/win terminal so they put no effort into making that experience good. If you are using an editor with integration the formatting confusion above is much less

**Comment by graysoncroom** [comment]
I understand what is happening now! I thought that error was from standard output instead of the repl showing me where the error was occuring. Sorry for my lack of understanding and thank you for taking the time to respond. 

I use vim and vim-slime to send bocks of code via tmux to a repl window. I have always used vim due to it being available when I first started using a linux machine. Maybe I will learn emacs someday, but I would rather focus on programming than another tool.

You can reject this pull request now.

**Comment by cbaggers** [comment]
Yeah it shouldnt be neccessary to have to switch to emacs. Have you tried [slimv](https://github.com/kovisoft/slimv)?

**Pull request closed without merging**
